// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package fr.treeptik.locationvoiture.builder;

import fr.treeptik.locationvoiture.model.Client;
import fr.treeptik.locationvoiture.model.Reservation;
import fr.treeptik.locationvoiture.model.Voiture;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClientBuilder extends ClientBuilderBase<ClientBuilder> {
	public static ClientBuilder client() {
		return new ClientBuilder();
	}

	public ClientBuilder() {
		super(new Client());
	}

	public Client build() {
		return getInstance();
	}
}

class ClientBuilderBase<GeneratorT extends ClientBuilderBase<GeneratorT>> {
	private Client instance;

	protected ClientBuilderBase(Client aInstance) {
		instance = aInstance;
	}

	protected Client getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withNom(String aValue) {
		instance.setNom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPrenom(String aValue) {
		instance.setPrenom(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withListReservations(List<Reservation> aValue) {
		instance.setListReservations(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedListReservation(Reservation aValue) {
		if (instance.getListReservations() == null) {
			instance.setListReservations(new ArrayList<Reservation>());
		}

		((ArrayList<Reservation>) instance.getListReservations()).add(aValue);

		return (GeneratorT) this;
	}

	public AddedListReservationReservationBuilder withAddedListReservation() {
		Reservation obj = new Reservation();

		withAddedListReservation(obj);

		return new AddedListReservationReservationBuilder(obj);
	}

	public class AddedListReservationReservationBuilder extends
			ReservationBuilderBase<AddedListReservationReservationBuilder> {
		public AddedListReservationReservationBuilder(Reservation aInstance) {
			super(aInstance);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT endListReservation() {
			return (GeneratorT) ClientBuilderBase.this;
		}
	}

	public static class ReservationBuilderBase<GeneratorT extends ReservationBuilderBase<GeneratorT>> {
		private Reservation instance;

		protected ReservationBuilderBase(Reservation aInstance) {
			instance = aInstance;
		}

		protected Reservation getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withId(Integer aValue) {
			instance.setId(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withDateResev(Date aValue) {
			instance.setdateResev(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withDatePrise(Date aValue) {
			instance.setDatePrise(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withDateRetour(Date aValue) {
			instance.setDateRetour(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withClient(Client aValue) {
			instance.setClient(aValue);

			return (GeneratorT) this;
		}

		public ClientClientBuilder withClient() {
			Client obj = new Client();

			withClient(obj);

			return new ClientClientBuilder(obj);
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withVoiture(Voiture aValue) {
			instance.setVoiture(aValue);

			return (GeneratorT) this;
		}

		public VoitureVoitureBuilder withVoiture() {
			Voiture obj = new Voiture();

			withVoiture(obj);

			return new VoitureVoitureBuilder(obj);
		}

		public class ClientClientBuilder extends
				ClientBuilderBase<ClientClientBuilder> {
			public ClientClientBuilder(Client aInstance) {
				super(aInstance);
			}

			@SuppressWarnings("unchecked")
			public GeneratorT endClient() {
				return (GeneratorT) ReservationBuilderBase.this;
			}
		}

		public class VoitureVoitureBuilder extends
				VoitureBuilderBase<VoitureVoitureBuilder> {
			public VoitureVoitureBuilder(Voiture aInstance) {
				super(aInstance);
			}

			@SuppressWarnings("unchecked")
			public GeneratorT endVoiture() {
				return (GeneratorT) ReservationBuilderBase.this;
			}
		}
	}

	public static class VoitureBuilderBase<GeneratorT extends VoitureBuilderBase<GeneratorT>> {
		private Voiture instance;

		protected VoitureBuilderBase(Voiture aInstance) {
			instance = aInstance;
		}

		protected Voiture getInstance() {
			return instance;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withId(Integer aValue) {
			instance.setId(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withMarque(String aValue) {
			instance.setMarque(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withModel(String aValue) {
			instance.setModel(aValue);

			return (GeneratorT) this;
		}

		@SuppressWarnings("unchecked")
		public GeneratorT withDateMiseEnCirculation(Date aValue) {
			instance.setDateMiseEnCirculation(aValue);

			return (GeneratorT) this;
		}
	}
}
