// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package fr.treeptik.locationvoiture.builder;

import fr.treeptik.locationvoiture.model.Voiture;
import java.util.Date;

public class VoitureBuilder extends VoitureBuilderBase<VoitureBuilder> {
	public static VoitureBuilder voiture() {
		return new VoitureBuilder();
	}

	public VoitureBuilder() {
		super(new Voiture());
	}

	public Voiture build() {
		return getInstance();
	}
}

class VoitureBuilderBase<GeneratorT extends VoitureBuilderBase<GeneratorT>> {
	private Voiture instance;

	protected VoitureBuilderBase(Voiture aInstance) {
		instance = aInstance;
	}

	protected Voiture getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Integer aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMarque(String aValue) {
		instance.setMarque(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withModel(String aValue) {
		instance.setModel(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDateMiseEnCirculation(Date aValue) {
		instance.setDateMiseEnCirculation(aValue);

		return (GeneratorT) this;
	}
}
